
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Quiénes Somos',
    'nav.services': 'Servicios',
    'nav.environments': 'Ambientes',
    'nav.contact': 'Contacto',
    'nav.schedule': 'Agendar Cita',
    
    // Home page
    'home.hero.title': 'Sonrisas Naturalmente',
    'home.hero.titleHighlight': 'Hermosas',
    'home.hero.description': 'Especialista en odontología estética y restauradora. Transformamos tu sonrisa con la más alta calidad y tecnología avanzada.',
    'home.hero.scheduleBtn': 'Agendar Consulta',
    'home.hero.servicesBtn': 'Ver Servicios',
    'home.stats.patients': 'Pacientes Satisfechos',
    'home.stats.experience': 'Años de Experiencia',
    'home.stats.treatments': 'Tratamientos Realizados',
    'home.stats.emergency': 'Emergencias',
    'home.results.title': 'Resultados que Hablan por Sí Solos',
    'home.results.description': 'Cada sonrisa es única y merece un tratamiento personalizado. Mira las transformaciones que hemos logrado.',
    'home.services.title': 'Nuestros Servicios',
    'home.services.description': 'Ofrecemos una amplia gama de tratamientos dentales especializados',
    'home.services.aesthetic': 'Odontología Estética',
    'home.services.aestheticDesc': 'Diseño de sonrisa, carillas, blanqueamiento dental',
    'home.services.restorative': 'Odontología Restauradora',
    'home.services.restorativeDesc': 'Coronas, puentes, implantes dentales',
    'home.services.preventive': 'Tratamientos Preventivos',
    'home.services.preventiveDesc': 'Limpiezas, sellantes, fluorización',
    'home.services.learnMore': 'Saber más →',
    
    // About page (Quiénes Somos)
    'about.hero.title': 'Conoce a la',
    'about.hero.titleHighlight': 'Dra. Liz Cheng',
    'about.hero.description': 'Especialista en odontología estética y restauradora, dedicada a crear sonrisas hermosas y saludables',
    'about.mission.title': 'Mi Misión',
    'about.mission.description1': 'Mi compromiso es brindar atención dental de la más alta calidad, combinando experiencia clínica, tecnología avanzada y un enfoque personalizado para cada paciente. Creo firmemente que una sonrisa saludable y hermosa puede transformar la vida de las personas.',
    'about.mission.description2': 'Con más de 15 años de experiencia en odontología estética y restauradora, me especializo en crear sonrisas naturalmente hermosas que reflejen la personalidad única de cada paciente.',
    'about.education.title': 'Formación y Experiencia',
    'about.education.description': 'Una sólida preparación académica respaldada por años de práctica clínica',
    'about.education.title1': 'Educación',
    'about.education.desc1': 'Doctora en Odontología\nUniversidad Cayetano Heredia\nEspecialización en Estética Dental',
    'about.education.title2': 'Certificaciones',
    'about.education.desc2': 'Certificada en Implantología\nEspecialista en Diseño de Sonrisa\nFormación en Técnicas Avanzadas',
    'about.education.title3': 'Filosofía',
    'about.education.desc3': 'Atención personalizada\nTratamientos mínimamente invasivos\nResultados naturales y duraderos',
    'about.values.title': 'Nuestros Valores',
    'about.values.quality': 'Calidad',
    'about.values.qualityDesc': 'Excelencia en cada tratamiento',
    'about.values.trust': 'Confianza',
    'about.values.trustDesc': 'Relaciones duraderas con nuestros pacientes',
    'about.values.innovation': 'Innovación',
    'about.values.innovationDesc': 'Tecnología y técnicas de vanguardia',
    'about.values.warmth': 'Calidez',
    'about.values.warmthDesc': 'Atención humana y personalizada',
    
    // Services page
    'services.hero.title': 'Nuestros',
    'services.hero.titleHighlight': 'Servicios',
    'services.hero.description': 'Ofrecemos una amplia gama de tratamientos dentales especializados con la más alta calidad y tecnología avanzada',
    'services.smileDesign.title': 'Diseño de Sonrisa',
    'services.smileDesign.description': 'Planificación digital personalizada para crear la sonrisa perfecta según tus características faciales.',
    'services.smileDesign.feature1': 'Análisis facial digital',
    'services.smileDesign.feature2': 'Planificación 3D',
    'services.smileDesign.feature3': 'Resultados predecibles',
    'services.veneers.title': 'Carillas Dentales',
    'services.veneers.description': 'Láminas ultrafinas de porcelana que transforman completamente tu sonrisa de manera conservadora.',
    'services.veneers.feature1': 'Mínima preparación dental',
    'services.veneers.feature2': 'Resultados naturales',
    'services.veneers.feature3': 'Larga duración',
    'services.whitening.title': 'Blanqueamiento Dental',
    'services.whitening.description': 'Tratamientos profesionales para lograr un blanqueamiento seguro y efectivo.',
    'services.whitening.feature1': 'Técnicas avanzadas',
    'services.whitening.feature2': 'Resultados inmediatos',
    'services.whitening.feature3': 'Seguro y controlado',
    'services.implants.title': 'Implantes Dentales',
    'services.implants.description': 'Reemplazo de dientes perdidos con implantes de titanio de alta calidad.',
    'services.implants.feature1': 'Titanio de grado médico',
    'services.implants.feature2': 'Integración natural',
    'services.implants.feature3': 'Solución permanente',
    'services.crowns.title': 'Coronas y Puentes',
    'services.crowns.description': 'Restauración de dientes dañados con coronas y puentes de porcelana.',
    'services.crowns.feature1': 'Porcelana de alta calidad',
    'services.crowns.feature2': 'Ajuste perfecto',
    'services.crowns.feature3': 'Apariencia natural',
    'services.preventive.title': 'Odontología Preventiva',
    'services.preventive.description': 'Cuidado preventivo para mantener tu sonrisa saludable a largo plazo.',
    'services.preventive.feature1': 'Limpiezas profesionales',
    'services.preventive.feature2': 'Aplicación de flúor',
    'services.preventive.feature3': 'Educación en higiene',
    'services.technology.title1': 'Tecnología de',
    'services.technology.title2': 'Vanguardia',
    'services.technology.description': 'Utilizamos la más avanzada tecnología dental para garantizar resultados precisos, cómodos y duraderos. Nuestro equipamiento de última generación nos permite ofrecer tratamientos más eficientes y con mayor precisión.',
    'services.technology.scanner.title': 'Escáner Intraoral 3D',
    'services.technology.scanner.desc': 'Impresiones digitales precisas sin molestias',
    'services.technology.cadcam.title': 'CAD/CAM',
    'services.technology.cadcam.desc': 'Diseño y fabricación asistida por computadora',
    'services.technology.microscopy.title': 'Microscopía Dental',
    'services.technology.microscopy.desc': 'Precisión máxima en todos los procedimientos',
    'services.cta.title': '¿Listo para Transformar tu Sonrisa?',
    'services.cta.description': 'Agenda tu consulta personalizada y descubre cómo podemos ayudarte a lograr la sonrisa de tus sueños',
    'services.cta.button': 'Agendar Consulta Ahora',
    
    // Environments page
    'environments.hero.title': 'Nuestros',
    'environments.hero.titleHighlight': 'Ambientes',
    'environments.hero.description': 'Espacios diseñados para tu comodidad y tranquilidad, equipados con la más moderna tecnología dental',
    'environments.gallery.office': 'Consultorio Principal',
    'environments.gallery.waiting': 'Sala de Espera',
    'environments.gallery.technology': 'Tecnología Avanzada',
    'environments.gallery.sterilization': 'Área de Esterilización',
    'environments.features.title': 'Características de Nuestras Instalaciones',
    'environments.features.description': 'Todo pensado para brindarte la mejor experiencia dental',
    'environments.features.sterilization.title': 'Esterilización Total',
    'environments.features.sterilization.desc': 'Protocolos estrictos de esterilización y desinfección',
    'environments.features.technology.title': 'Tecnología Avanzada',
    'environments.features.technology.desc': 'Equipamiento de última generación para mejores resultados',
    'environments.features.relaxing.title': 'Ambiente Relajante',
    'environments.features.relaxing.desc': 'Espacios diseñados para reducir la ansiedad dental',
    'environments.features.privacy.title': 'Privacidad Total',
    'environments.features.privacy.desc': 'Consultorios privados para tu comodidad y confidencialidad',
    'environments.cta.title': '¿Te gustaría conocer nuestras instalaciones?',
    'environments.cta.description': 'Agenda una visita y descubre por qué nuestros pacientes se sienten cómodos y seguros en nuestro consultorio',
    'environments.cta.button': 'Agendar Visita',
    
    // Contact page
    'contact.hero.title': 'Contáctanos',
    'contact.hero.description': 'Estamos aquí para responder todas tus preguntas y ayudarte a conseguir la sonrisa de tus sueños',
    'contact.info.title': 'Información de Contacto',
    'contact.info.address': 'Dirección',
    'contact.info.phone': 'Teléfono',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Horarios de Atención',
    'contact.info.hoursText': 'Lunes - Viernes: 9:00 AM - 7:00 PM (previa cita)\nSábados y Domingos: Cerrado',
    'contact.info.whatsapp': 'WhatsApp',
    'contact.info.whatsappDesc': 'Para consultas rápidas y citas',
    'contact.info.whatsappBtn': 'Enviar Mensaje',
    'contact.emergency.title': '¿Tienes una Emergencia Dental?',
    'contact.emergency.description': 'Para emergencias dentales fuera del horario de atención, contáctanos por WhatsApp. Te responderemos lo antes posible.',
    'contact.emergency.button': 'Contactar por Emergencia',
    'contact.cta.title': '¿Listo para Comenzar?',
    'contact.cta.description': 'Agenda tu consulta hoy mismo y da el primer paso hacia la sonrisa de tus sueños',
    'contact.cta.button': 'Agendar Consulta',
    
    // 404 page
    'notfound.title': 'Página No Encontrada',
    'notfound.description': 'Lo sentimos, la página que estás buscando no existe. Puede que haya sido movida, eliminada o que hayas ingresado una URL incorrecta.',
    'notfound.homeBtn': 'Ir al Inicio',
    'notfound.backBtn': 'Volver Atrás',
    'notfound.links.title': 'Enlaces Útiles',
    'notfound.links.description': 'Quizás estabas buscando alguna de estas páginas',
    'notfound.links.aboutTitle': 'Quiénes Somos',
    'notfound.links.aboutDesc': 'Conoce a la Dra. Liz Cheng',
    'notfound.links.servicesTitle': 'Servicios',
    'notfound.links.servicesDesc': 'Nuestros tratamientos',
    'notfound.links.environmentsTitle': 'Ambientes',
    'notfound.links.environmentsDesc': 'Nuestras instalaciones',
    'notfound.links.contactTitle': 'Contacto',
    'notfound.links.contactDesc': 'Información de contacto',
    
    // Footer
    'footer.description': 'Odontología estética y restauradora con la más alta calidad y tecnología avanzada.',
    'footer.contact': 'Contacto',
    'footer.schedule': 'Horarios de Atención',
    'footer.scheduleText': 'Lunes - Viernes: 9:00 AM - 7:00 PM (previa cita)',
    'footer.weekends': 'Sábados y Domingos: Cerrado',
    'footer.followUs': 'Síguenos',
    'footer.socialText': 'Mantente conectado para tips de salud dental y noticias.',
    'footer.copyright': '© 2025 Dra. Liz Cheng - Odontología Estética y Restauradora. Todos los derechos reservados.',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.environments': 'Facilities',
    'nav.contact': 'Contact',
    'nav.schedule': 'Schedule Appointment',
    
    // Home page
    'home.hero.title': 'Naturally Beautiful',
    'home.hero.titleHighlight': 'Smiles',
    'home.hero.description': 'Specialist in aesthetic and restorative dentistry. We transform your smile with the highest quality and advanced technology.',
    'home.hero.scheduleBtn': 'Schedule Consultation',
    'home.hero.servicesBtn': 'View Services',
    'home.stats.patients': 'Satisfied Patients',
    'home.stats.experience': 'Years of Experience',
    'home.stats.treatments': 'Treatments Performed',
    'home.stats.emergency': 'Emergency Care',
    'home.results.title': 'Results That Speak for Themselves',
    'home.results.description': 'Each smile is unique and deserves personalized treatment. See the transformations we have achieved.',
    'home.services.title': 'Our Services',
    'home.services.description': 'We offer a wide range of specialized dental treatments',
    'home.services.aesthetic': 'Aesthetic Dentistry',
    'home.services.aestheticDesc': 'Smile design, veneers, teeth whitening',
    'home.services.restorative': 'Restorative Dentistry',
    'home.services.restorativeDesc': 'Crowns, bridges, dental implants',
    'home.services.preventive': 'Preventive Treatments',
    'home.services.preventiveDesc': 'Cleanings, sealants, fluoride treatments',
    'home.services.learnMore': 'Learn more →',
    
    // About page (Quiénes Somos)
    'about.hero.title': 'Meet',
    'about.hero.titleHighlight': 'Dr. Liz Cheng',
    'about.hero.description': 'Specialist in aesthetic and restorative dentistry, dedicated to creating beautiful and healthy smiles',
    'about.mission.title': 'My Mission',
    'about.mission.description1': 'My commitment is to provide the highest quality dental care, combining clinical experience, advanced technology and a personalized approach for each patient. I firmly believe that a healthy and beautiful smile can transform people\'s lives.',
    'about.mission.description2': 'With over 15 years of experience in aesthetic and restorative dentistry, I specialize in creating naturally beautiful smiles that reflect each patient\'s unique personality.',
    'about.education.title': 'Education and Experience',
    'about.education.description': 'Solid academic preparation backed by years of clinical practice',
    'about.education.title1': 'Education',
    'about.education.desc1': 'Doctor of Dentistry\nCayetano Heredia University\nSpecialization in Aesthetic Dentistry',
    'about.education.title2': 'Certifications',
    'about.education.desc2': 'Certified in Implantology\nSmile Design Specialist\nAdvanced Techniques Training',
    'about.education.title3': 'Philosophy',
    'about.education.desc3': 'Personalized care\nMinimally invasive treatments\nNatural and lasting results',
    'about.values.title': 'Our Values',
    'about.values.quality': 'Quality',
    'about.values.qualityDesc': 'Excellence in every treatment',
    'about.values.trust': 'Trust',
    'about.values.trustDesc': 'Lasting relationships with our patients',
    'about.values.innovation': 'Innovation',
    'about.values.innovationDesc': 'Cutting-edge technology and techniques',
    'about.values.warmth': 'Warmth',
    'about.values.warmthDesc': 'Human and personalized care',
    
    // Services page
    'services.hero.title': 'Our',
    'services.hero.titleHighlight': 'Services',
    'services.hero.description': 'We offer a wide range of specialized dental treatments with the highest quality and advanced technology',
    'services.smileDesign.title': 'Smile Design',
    'services.smileDesign.description': 'Personalized digital planning to create the perfect smile according to your facial characteristics.',
    'services.smileDesign.feature1': 'Digital facial analysis',
    'services.smileDesign.feature2': '3D planning',
    'services.smileDesign.feature3': 'Predictable results',
    'services.veneers.title': 'Dental Veneers',
    'services.veneers.description': 'Ultra-thin porcelain laminates that completely transform your smile in a conservative way.',
    'services.veneers.feature1': 'Minimal tooth preparation',
    'services.veneers.feature2': 'Natural results',
    'services.veneers.feature3': 'Long-lasting',
    'services.whitening.title': 'Teeth Whitening',
    'services.whitening.description': 'Professional treatments to achieve safe and effective whitening.',
    'services.whitening.feature1': 'Advanced techniques',
    'services.whitening.feature2': 'Immediate results',
    'services.whitening.feature3': 'Safe and controlled',
    'services.implants.title': 'Dental Implants',
    'services.implants.description': 'Replacement of lost teeth with high-quality titanium implants.',
    'services.implants.feature1': 'Medical grade titanium',
    'services.implants.feature2': 'Natural integration',
    'services.implants.feature3': 'Permanent solution',
    'services.crowns.title': 'Crowns and Bridges',
    'services.crowns.description': 'Restoration of damaged teeth with porcelain crowns and bridges.',
    'services.crowns.feature1': 'High-quality porcelain',
    'services.crowns.feature2': 'Perfect fit',
    'services.crowns.feature3': 'Natural appearance',
    'services.preventive.title': 'Preventive Dentistry',
    'services.preventive.description': 'Preventive care to keep your smile healthy long-term.',
    'services.preventive.feature1': 'Professional cleanings',
    'services.preventive.feature2': 'Fluoride application',
    'services.preventive.feature3': 'Hygiene education',
    'services.technology.title1': 'Cutting-edge',
    'services.technology.title2': 'Technology',
    'services.technology.description': 'We use the most advanced dental technology to guarantee precise, comfortable and long-lasting results. Our state-of-the-art equipment allows us to offer more efficient treatments with greater precision.',
    'services.technology.scanner.title': '3D Intraoral Scanner',
    'services.technology.scanner.desc': 'Precise digital impressions without discomfort',
    'services.technology.cadcam.title': 'CAD/CAM',
    'services.technology.cadcam.desc': 'Computer-aided design and manufacturing',
    'services.technology.microscopy.title': 'Dental Microscopy',
    'services.technology.microscopy.desc': 'Maximum precision in all procedures',
    'services.cta.title': 'Ready to Transform Your Smile?',
    'services.cta.description': 'Schedule your personalized consultation and discover how we can help you achieve the smile of your dreams',
    'services.cta.button': 'Schedule Consultation Now',
    
    // Environments page
    'environments.hero.title': 'Our',
    'environments.hero.titleHighlight': 'Facilities',
    'environments.hero.description': 'Spaces designed for your comfort and peace of mind, equipped with the most modern dental technology',
    'environments.gallery.office': 'Main Office',
    'environments.gallery.waiting': 'Waiting Room',
    'environments.gallery.technology': 'Advanced Technology',
    'environments.gallery.sterilization': 'Sterilization Area',
    'environments.features.title': 'Our Facilities Features',
    'environments.features.description': 'Everything designed to give you the best dental experience',
    'environments.features.sterilization.title': 'Complete Sterilization',
    'environments.features.sterilization.desc': 'Strict sterilization and disinfection protocols',
    'environments.features.technology.title': 'Advanced Technology',
    'environments.features.technology.desc': 'State-of-the-art equipment for better results',
    'environments.features.relaxing.title': 'Relaxing Environment',
    'environments.features.relaxing.desc': 'Spaces designed to reduce dental anxiety',
    'environments.features.privacy.title': 'Complete Privacy',
    'environments.features.privacy.desc': 'Private offices for your comfort and confidentiality',
    'environments.cta.title': 'Would you like to see our facilities?',
    'environments.cta.description': 'Schedule a visit and discover why our patients feel comfortable and safe in our office',
    'environments.cta.button': 'Schedule Visit',
    
    // Contact page
    'contact.hero.title': 'Contact Us',
    'contact.hero.description': 'We are here to answer all your questions and help you get the smile of your dreams',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Address',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.hours': 'Office Hours',
    'contact.info.hoursText': 'Monday - Friday: 9:00 AM - 7:00 PM (by appointment)\nSaturdays and Sundays: Closed',
    'contact.info.whatsapp': 'WhatsApp',
    'contact.info.whatsappDesc': 'For quick questions and appointments',
    'contact.info.whatsappBtn': 'Send Message',
    'contact.emergency.title': 'Do you have a Dental Emergency?',
    'contact.emergency.description': 'For dental emergencies outside office hours, contact us via WhatsApp. We will respond as soon as possible.',
    'contact.emergency.button': 'Contact for Emergency',
    'contact.cta.title': 'Ready to Get Started?',
    'contact.cta.description': 'Schedule your consultation today and take the first step towards the smile of your dreams',
    'contact.cta.button': 'Schedule Consultation',
    
    // 404 page
    'notfound.title': 'Page Not Found',
    'notfound.description': 'Sorry, the page you are looking for does not exist. It may have been moved, deleted, or you may have entered an incorrect URL.',
    'notfound.homeBtn': 'Go Home',
    'notfound.backBtn': 'Go Back',
    'notfound.links.title': 'Useful Links',
    'notfound.links.description': 'Maybe you were looking for one of these pages',
    'notfound.links.aboutTitle': 'About Us',
    'notfound.links.aboutDesc': 'Meet Dr. Liz Cheng',
    'notfound.links.servicesTitle': 'Services',
    'notfound.links.servicesDesc': 'Our treatments',
    'notfound.links.environmentsTitle': 'Facilities',
    'notfound.links.environmentsDesc': 'Our facilities',
    'notfound.links.contactTitle': 'Contact',
    'notfound.links.contactDesc': 'Contact information',
    
    // Footer
    'footer.description': 'Aesthetic and restorative dentistry with the highest quality and advanced technology.',
    'footer.contact': 'Contact',
    'footer.schedule': 'Office Hours',
    'footer.scheduleText': 'Monday - Friday: 9:00 AM - 7:00 PM (by appointment)',
    'footer.weekends': 'Saturdays and Sundays: Closed',
    'footer.followUs': 'Follow Us',
    'footer.socialText': 'Stay connected for dental health tips and news.',
    'footer.copyright': '© 2025 Dr. Liz Cheng - Aesthetic and Restorative Dentistry. All rights reserved.',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('es'); // Default to Spanish

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['es']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
